apiVersion: v1
kind: Service
metadata:
  name: menuservice
spec:
  type: NodePort
  selector:
    app: menu
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 8080
      targetPort: 8080
      
