apiVersion: v1
kind: Service
metadata:
  name: customerservice
spec:
  type: NodePort
  selector:
    app: customer
  ports:
    - protocol: TCP
      nodePort: 31234
      port: 8000
      targetPort: 8000

      
