apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - protocol: TCP
      nodePort: 30083
      port: 9000
      targetPort: 9000